### ISSUE TITLE
100% CPU after adding an executor to loop

### ISSUE THREAD

**Issue by detly** [Smithay/calloop#34] opened 2021-02-07 15:18 UTC
I was trying to integrate [`async_process`](https://docs.rs/async-process/1.0.2/async_process/index.html) into calloop when I found my CPU usage would spike. I initially thought it was perhaps an incompatible combination, but then I reduced it to this example without `async_process`:

```rust
use calloop::futures::executor;
use calloop::signals::{Signal, Signals};
use calloop::{EventLoop, LoopHandle, LoopSignal};
use env_logger::Env;
use log::*;

fn add_future_to_loop<T>(handle: &LoopHandle<T>) {
    let (exec, _) = executor::<()>().unwrap();
    handle.insert_source(exec, |_, _, _| {}).unwrap();
}

fn main() {
    // Set up logging (trace level by default).
    env_logger::Builder::from_env(Env::default().default_filter_or("trace"))
        .format_timestamp(None)
        .init();

    // Event loop initialisation.
    let mut event_loop: EventLoop<LoopSignal> =
        EventLoop::try_new().expect("Could not initialise event loop");

    // Exit on interrupt (for Ctrl-C when running in console) and terminate (for
    // OpenWrt's service control).
    const SIGNALS_TO_STOP_ON: &[Signal] = &[Signal::SIGINT, Signal::SIGTERM];

    let handle = event_loop.handle();

    let mut signaller = event_loop.get_signal();

    handle
        .insert_source(
            Signals::new(SIGNALS_TO_STOP_ON).unwrap(),
            |event, _metadata, signaller| {
                info!("Signal received: {}", event.signal());
                signaller.stop();
            },
        )
        .unwrap();

    add_future_to_loop(&handle);

    event_loop
        .run(None, &mut signaller, |_| {})
        .expect("Could not run event loop");
}
```

Have I missed something in how to use this? I'm running this on Ubuntu 20.10 with rustc 1.49 via rustup. Calloop is v0.7.1.

**Comment by vberger** [comment] 2021-02-07 21:47
That definitely looks like a calloop bug, I'll investigate, thanks for the reproducing example!

**Comment by detly** [comment] 2021-02-08 00:35
Demonstration of workaround using threads for now if anyone else needs it:

```rust
use std::io::Result;
use std::process::{Command, ExitStatus};
use std::thread;

use calloop::channel::{channel, Event};
use calloop::LoopHandle;

fn add_sleep_to_loop<T>(handle: &LoopHandle<T>, seconds: u64) {
    let (send, chan) = channel::<Result<ExitStatus>>();

    thread::spawn(move || {
        let status = Command::new("sleep").arg(format!("{}s", seconds)).status();
        send.send(status).unwrap();
    });

    handle
        .insert_source(chan, |msg, _, _| {
            if let Event::Msg(status) = msg {
                if status.unwrap().success() {
                    println!("Command succeeded");
                }
                else {
                    println!("Command failed");
                }
            }
        })
        .unwrap();
}
```

**Comment by detly** [comment] 2021-02-08 00:47
Ah wait no, that also results in 100% CPU! Minimal example:

```rust
fn add_sleep_to_loop<T>(handle: &LoopHandle<T>, _: u64) {
    let (_, chan) = channel::<Result<ExitStatus>>();
    handle
        .insert_source(chan, |_, _, _| {})
        .unwrap();
}
```

**Comment by vberger** [comment] 2021-02-08 09:55
Okay, got it, it is indeed a bug in calloop: when the "sending" end of a channel/executor/ping is destroyed, the receiving end is infinitely considered as readable by the event loop, rather than being unregistered.

**Comment by vberger** [comment] 2021-02-08 10:27
Could you confirm whether this PR https://github.com/Smithay/calloop/pull/35 solves the issue for you ?

**Comment by detly** [comment] 2021-02-08 12:19
No more 100% CPU, but this code:

```rust
use async_process::{Command, ExitStatus};
use calloop::futures::executor;
use calloop::signals::{Signal, Signals};
use calloop::timer::Timer;
use calloop::{EventLoop, LoopHandle, LoopSignal};
use env_logger::Env;
use log::*;

fn add_sleep_to_loop<T>(handle: &LoopHandle<T>, seconds: u64) {
    let (exec, sched) = executor::<std::io::Result<ExitStatus>>().unwrap();

    let cmd = Command::new("sleep").arg(format!("{}s", seconds)).status();

    handle
        .insert_source(exec, |status, _, _| {
            if status.unwrap().success() {
                println!("Command succeeded");
            }
            else {
                println!("Command failed");
            }
        })
        .unwrap();

    sched.schedule(cmd).unwrap();
}

fn main() {
    // Set up logging (trace level by default).
    env_logger::Builder::from_env(Env::default().default_filter_or("trace"))
        .format_timestamp(None)
        .init();

    // Event loop initialisation.
    let mut event_loop: EventLoop<LoopSignal> =
        EventLoop::try_new().expect("Could not initialise event loop");

    // Exit on interrupt (for Ctrl-C when running in console) and terminate (for
    // OpenWrt's service control).
    const SIGNALS_TO_STOP_ON: &[Signal] = &[Signal::SIGINT, Signal::SIGTERM];

    let handle = event_loop.handle();

    let mut signaller = event_loop.get_signal();

    handle
        .insert_source(
            Signals::new(SIGNALS_TO_STOP_ON).unwrap(),
            |event, _metadata, signaller| {
                info!("Signal received: {}", event.signal());
                signaller.stop();
            },
        )
        .unwrap();

    add_sleep_to_loop(&handle, 9);

    event_loop
        .run(None, &mut signaller, |_| {})
        .expect("Could not run event loop");
}
```

...results in this error:

```plain
    Finished dev [unoptimized + debuginfo] target(s) in 1.08s
     Running `target/debug/calloop-test`
thread 'main' panicked at 'Could not run event loop: Os { code: 9, kind: Other, message: "Bad file descriptor" }', src/main.rs:86:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(The line numbers will be off, but 86 is the event loop run call.)

**Comment by detly** [comment] 2021-02-08 12:29
If I pass the `sched` end of the `executor()` return value out and keep ownership of it in `main()`, then I don't get the error. It's not exactly surprising to me that this is needed, since the alternative is, as you say, acting as though dropped `Scheduler` objects are perpetually alive forever more. However it might be wise to document this. There's probably an alternative too that I haven't thought of.

**Comment by detly** [comment] 2021-02-08 13:58
Adding `drop(sched.clone())` to the end of the callback works too.

**Comment by vberger** [comment] 2021-02-08 14:21
Ah indeed, there was *also* a bug in the executor code, which did not correctly process its readiness event source, causing it to be indefinitely ready as soon as a single future was ready. I've update the PR, how is it now ?

**Comment by detly** [comment] 2021-02-09 01:15
Woohoo it works perfectly! No CPU maxout, no errors.

**Comment by vberger** [comment] 2021-02-09 17:36
Calloop `0.7.2` is released with the bugfix.

**Closed by vberger** 2021-02-09 17:36 UTC
Labels: bug
